version: '{build}'
skip_tags: true

environment:
  access_token:
    secure: DOOS4g7CT8ctOgiMr62K56qQ1FO6s2ESpqNZlhf8F4nomemvvwxV/pRj9nbKmtjR

install:
  - git submodule update --init --recursive

  # environment and system dependency
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha10-windows.zip
  
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name http://downloads.sourceforge.net/freetype/freetype-2.7.tar.bz2 ; exit 0"
  - tar xf freetype-2.7.tar.bz2
  - move freetype-2.7 freetype
  
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip ; exit 0"
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.2.4.tar.gz ; exit 0"
  - tar xf lua-5.2.4.tar.gz
  - move lua-5.2.4\src lua
  
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name https://www.sqlite.org/2016/sqlite-amalgamation-3150200.zip ; exit 0"
  - 7z x sqlite-amalgamation-3150200.zip
  - move sqlite-amalgamation-3150200 sqlite3

  # let premake happy
  - xcopy /E premake\* .
  
  # patch irrlicht
  - patch -p1 < irrlicht\irrlicht.patch
  
  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - mv bin\release\ygopro.exe .
  - mkdir deck
  - mkdir pics
  - mkdir replay
  - bash -c "curl --retry 5 --location --remote-header-name --remote-name https://github.com/mercury233/ygopro/raw/server/cards.cdb ; exit 0"
  - 7z a ygopro-ver.233.7z ygopro.exe LICENSE README.md lflist.conf strings.conf system.conf cards.cdb script textures deck pics replay -xr!.git*

  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - bash -c "git tag -d latest ; exit 0"
  - git tag latest HEAD
  - git push -f origin latest

test: off

artifacts:
  - path: ygopro.exe
    name: ygopro
  - path: ygopro-ver.233.7z
    name: ygopro-ver.233

deploy:
    release: latest
    description: 'Automatic Build by Appveyor'
    provider: GitHub
    auth_token: $(access_token)
    force_update: true
    on:
        branch: master

cache:
  - premake-5.0.0-alpha10-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - freetype-2.7.tar.bz2
  - irrlicht-1.8.4.zip
  - lua-5.2.4.tar.gz
  - sqlite-amalgamation-3150200.zip
